spring.application.name=ms-perfiles
server.port=${SERVER_PORT:8082}

spring.datasource.url=${DATABASE_URL:${MS_PERFILES_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:style_beauty}}}
spring.datasource.username=${DATABASE_USER:${MS_PERFILES_DATASOURCE_USERNAME:}}
spring.datasource.password=${DATABASE_PASSWORD:${MS_PERFILES_DATASOURCE_PASSWORD:}}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.connection-init-sql=SET CLIENT_ENCODING TO 'UTF8'

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
