spring.application.name=ms-notificacion-audit
server.port=${SERVER_PORT:8088}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/style_beauty_audit}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
