spring.application.name=ms-catalogo
server.port=${SERVER_PORT:8083}

spring.datasource.url=${DATABASE_URL:${MS_CATALOGO_DATASOURCE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:style_beauty}}}
spring.datasource.username=${DATABASE_USER:${MS_CATALOGO_DATASOURCE_USERNAME:}}
spring.datasource.password=${DATABASE_PASSWORD:${MS_CATALOGO_DATASOURCE_PASSWORD:}}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
