spring.application.name=ms-cliente

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.klsfczwikscycexbivon
spring.datasource.password=Matimaxi123.


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
