spring.application.name=Api-gateway
server.port=${SERVER_PORT:8080}
server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY:framework}

spring.codec.max-in-memory-size=${SPRING_CODEC_MAX_IN_MEMORY_SIZE:6MB}

spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST

spring.cloud.gateway.server.webflux.routes[0].id=ms-auth
spring.cloud.gateway.server.webflux.routes[0].uri=${MS_AUTH_URI:http://ms-auth:8081}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=ms-perfiles
spring.cloud.gateway.server.webflux.routes[1].uri=${MS_PERFILES_URI:http://ms-perfiles:8082}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/perfiles/**,/api/profesionales/**,/api/admin/**,/api/contact,/api/contact/**

spring.cloud.gateway.server.webflux.routes[2].id=ms-catalogo
spring.cloud.gateway.server.webflux.routes[2].uri=${MS_CATALOGO_URI:http://ms-catalogo:8083}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/servicio/**,/api/servicios/**,/api/servicio-staff/**,/api/catalogo/**

spring.cloud.gateway.server.webflux.routes[3].id=ms-agenda
spring.cloud.gateway.server.webflux.routes[3].uri=${MS_AGENDA_URI:http://ms-agenda:8084}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/agenda/**

spring.cloud.gateway.server.webflux.routes[4].id=ms-inventario
spring.cloud.gateway.server.webflux.routes[4].uri=${MS_INVENTARIO_URI:http://ms-inventario:8085}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/inventarios/**,/api/productos/**

spring.cloud.gateway.server.webflux.routes[5].id=ms-pagos
spring.cloud.gateway.server.webflux.routes[5].uri=${MS_PAGOS_URI:http://ms-pagos:8086}
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.server.webflux.routes[6].id=ms-extra
spring.cloud.gateway.server.webflux.routes[6].uri=${MS_EXTRA_URI:http://ms-extra:8087}
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/extra/**

spring.cloud.gateway.server.webflux.routes[7].id=ms-notificacion-audit
spring.cloud.gateway.server.webflux.routes[7].uri=${MS_NOTIFICACION_AUDIT_URI:http://ms-notificacion-audit:8088}
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/notificacion/**,/api/audit/**

springdoc.swagger-ui.urls[0].name=auth
springdoc.swagger-ui.urls[0].url=/aggregate/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=perfiles
springdoc.swagger-ui.urls[1].url=/aggregate/perfiles/v3/api-docs
springdoc.swagger-ui.urls[2].name=catalogo
springdoc.swagger-ui.urls[2].url=/aggregate/catalogo/v3/api-docs
springdoc.swagger-ui.urls[3].name=agenda
springdoc.swagger-ui.urls[3].url=/aggregate/agenda/v3/api-docs
springdoc.swagger-ui.urls[4].name=inventario
springdoc.swagger-ui.urls[4].url=/aggregate/inventario/v3/api-docs
springdoc.swagger-ui.urls[5].name=pagos
springdoc.swagger-ui.urls[5].url=/aggregate/pagos/v3/api-docs
springdoc.swagger-ui.urls[6].name=extra
springdoc.swagger-ui.urls[6].url=/aggregate/extra/v3/api-docs
springdoc.swagger-ui.urls[7].name=notificacion-audit
springdoc.swagger-ui.urls[7].url=/aggregate/notificacion-audit/v3/api-docs

spring.cloud.gateway.server.webflux.routes[8].id=swagger-auth
spring.cloud.gateway.server.webflux.routes[8].uri=${MS_AUTH_URI:http://ms-auth:8081}
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/aggregate/auth/v3/api-docs
spring.cloud.gateway.server.webflux.routes[8].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[9].id=swagger-perfiles
spring.cloud.gateway.server.webflux.routes[9].uri=${MS_PERFILES_URI:http://ms-perfiles:8082}
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/aggregate/perfiles/v3/api-docs
spring.cloud.gateway.server.webflux.routes[9].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[10].id=swagger-catalogo
spring.cloud.gateway.server.webflux.routes[10].uri=${MS_CATALOGO_URI:http://ms-catalogo:8083}
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/aggregate/catalogo/v3/api-docs
spring.cloud.gateway.server.webflux.routes[10].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[11].id=swagger-agenda
spring.cloud.gateway.server.webflux.routes[11].uri=${MS_AGENDA_URI:http://ms-agenda:8084}
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/aggregate/agenda/v3/api-docs
spring.cloud.gateway.server.webflux.routes[11].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[12].id=swagger-inventario
spring.cloud.gateway.server.webflux.routes[12].uri=${MS_INVENTARIO_URI:http://ms-inventario:8085}
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/aggregate/inventario/v3/api-docs
spring.cloud.gateway.server.webflux.routes[12].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[13].id=swagger-pagos
spring.cloud.gateway.server.webflux.routes[13].uri=${MS_PAGOS_URI:http://ms-pagos:8086}
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/aggregate/pagos/v3/api-docs
spring.cloud.gateway.server.webflux.routes[13].filters[0]=SetPath=/v3/api-docs
spring.cloud.gateway.server.webflux.routes[13].filters[1]=AddRequestHeader=Authorization, Basic YWRtaW46YWRtaW4xMjM=

spring.cloud.gateway.server.webflux.routes[14].id=swagger-extra
spring.cloud.gateway.server.webflux.routes[14].uri=${MS_EXTRA_URI:http://ms-extra:8087}
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/aggregate/extra/v3/api-docs
spring.cloud.gateway.server.webflux.routes[14].filters[0]=SetPath=/v3/api-docs

spring.cloud.gateway.server.webflux.routes[15].id=swagger-notificacion-audit
spring.cloud.gateway.server.webflux.routes[15].uri=${MS_NOTIFICACION_AUDIT_URI:http://ms-notificacion-audit:8088}
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/aggregate/notificacion-audit/v3/api-docs
spring.cloud.gateway.server.webflux.routes[15].filters[0]=SetPath=/v3/api-docs
spring.cloud.gateway.server.webflux.routes[15].filters[1]=AddRequestHeader=Authorization, Basic YWRtaW46YWRtaW4xMjM=

spring.cloud.gateway.server.webflux.routes[16].id=root-redirect
spring.cloud.gateway.server.webflux.routes[16].uri=no://op
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/
spring.cloud.gateway.server.webflux.routes[16].filters[0]=RedirectTo=302,/swagger-ui.html
