spring.application.name=ms-pagos
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5436/ms_pagos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false