spring.application.name=ms-pagos
server.port=${SERVER_PORT:8086}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/style_beauty}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

tbk.commerce-code=${TBK_COMMERCE_CODE:597055555532}
tbk.api-key=${TBK_API_KEY:579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C}
tbk.return-url=${TBK_RETURN_URL:http://localhost:8080/api/pagos/webpay/retorno}

ms.agenda.base-url=${MS_AGENDA_BASE_URL:http://localhost:8084}
ms.catalogo.base-url=${MS_CATALOGO_BASE_URL:http://localhost:8083}
